// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dBvZINB_Expt_vec
void dBvZINB_Expt_vec(int *xvec, int *yvec, int *freq, int *n, double *a0, double *a1, double *a2, double *b1, double *b2, double *p1, double *p2, double *p3, double *p4, NumericVector *result);
RcppExport SEXP _bzinb_dBvZINB_Expt_vec(SEXP *xvecSEXP, SEXP *yvecSEXP, SEXP *freqSEXP, SEXP *nSEXP, SEXP *a0SEXP, SEXP *a1SEXP, SEXP *a2SEXP, SEXP *b1SEXP, SEXP *b2SEXP, SEXP *p1SEXP, SEXP *p2SEXP, SEXP *p3SEXP, SEXP *p4SEXP, SEXP *resultSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type *xvec(*xvecSEXP);
    Rcpp::traits::input_parameter< int >::type *yvec(*yvecSEXP);
    Rcpp::traits::input_parameter< int >::type *freq(*freqSEXP);
    Rcpp::traits::input_parameter< int >::type *n(*nSEXP);
    Rcpp::traits::input_parameter< double >::type *a0(*a0SEXP);
    Rcpp::traits::input_parameter< double >::type *a1(*a1SEXP);
    Rcpp::traits::input_parameter< double >::type *a2(*a2SEXP);
    Rcpp::traits::input_parameter< double >::type *b1(*b1SEXP);
    Rcpp::traits::input_parameter< double >::type *b2(*b2SEXP);
    Rcpp::traits::input_parameter< double >::type *p1(*p1SEXP);
    Rcpp::traits::input_parameter< double >::type *p2(*p2SEXP);
    Rcpp::traits::input_parameter< double >::type *p3(*p3SEXP);
    Rcpp::traits::input_parameter< double >::type *p4(*p4SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type *result(*resultSEXP);
    dBvZINB_Expt_vec(*xvec, *yvec, *freq, *n, *a0, *a1, *a2, *b1, *b2, *p1, *p2, *p3, *p4, *result);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bzinb_dBvZINB_Expt_vec", (DL_FUNC) &_bzinb_dBvZINB_Expt_vec, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_bzinb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
