# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dBvZINB_Expt <- function(x, y, a0, a1, a2, b1, b2, p1, p2, p3, p4, result) {
    invisible(.Call('_bzinb_dBvZINB_Expt', PACKAGE = 'bzinb', x, y, a0, a1, a2, b1, b2, p1, p2, p3, p4, result))
}

